name: Deploy to Fastly

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Allow the workflow to download release assets (Fastly CLI) from GitHub
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Make the token available to all steps, including any "pre" scripts
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node (for js-compute bundling)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (if package.json exists)
        run: |
          if [ -f package.json ]; then npm ci --no-audit --fund=false; fi

      # ✅ Install the Fastly CLI explicitly (pinned) using a GitHub token
      - name: Install Fastly CLI
        uses: fastly/cli-action@v3
        with:
          version: v11.4.0
          github-token: ${{ github.token }}

      # ✅ With CLI present, the compute action won't fail its "pre" step
      - name: Build & deploy to Fastly Compute
        uses: fastly/compute-actions@v5
        with:
          token: ${{ secrets.FASTLY_API_TOKEN }}        # Fastly automation token (repo secret)
          service_id: ${{ secrets.FASTLY_SERVICE_ID }}  # Fastly service ID (repo secret)
          project_directory: .
          verbose: true
