name: Deploy to Fastly

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build & deploy to Fastly Compute
        uses: fastly/compute-actions@v5
        with:
          token: ${{ secrets.FASTLY_API_TOKEN }}      # ← your Fastly token (repo secret)
          service_id: ${{ secrets.FASTLY_SERVICE_ID }}# ← your Fastly service ID (repo secret)
          comment: "GitHub Actions deploy ${{ github.sha }}"
