name: Deploy to Fastly

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      FASTLY_CLI_VERSION: v11.4.0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Install Fastly CLI (tries both asset name patterns)
      - name: Install Fastly CLI
        run: |
          set -euxo pipefail
          URL1="https://github.com/fastly/cli/releases/download/${FASTLY_CLI_VERSION}/fastly_${FASTLY_CLI_VERSION}_linux_amd64.tar.gz"
          URL2="https://github.com/fastly/cli/releases/download/${FASTLY_CLI_VERSION}/fastly_${FASTLY_CLI_VERSION#v}_linux_amd64.tar.gz"
          curl -fSLo fastly.tgz "$URL1" || curl -fSLo fastly.tgz "$URL2"
          tar -xzf fastly.tgz
          sudo mv fastly*/fastly /usr/local/bin/fastly
          fastly --version

      - name: Build Compute package
        run: |
          set -euxo pipefail
          fastly compute build --non-interactive

      - name: Deploy to Fastly
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
          FASTLY_SERVICE_ID: ${{ secrets.FASTLY_SERVICE_ID }}
        run: |
          set -euxo pipefail
          fastly compute deploy \
            --non-interactive \
            --service-id "$FASTLY_SERVICE_ID" \
            --token "$FASTLY_API_TOKEN"
